### ISSUE TITLE
figure out how to tell that whereami was called from knitr chunk

### ISSUE THREAD

**Issue by yonicd** [yonicd/whereami#1]
trying to get the parent chunk name that called `whereami()`. 

best idea i had is to have a formal arg that gets called when whereami is invoked in a chunk, but i cant find any opts that hold the chunk name.

any ideas @maelle @colinfay @krlmlr? it looks like the script has no idea what parent env called it.

**Comment by yonicd** [comment]
got most of the way there with this commit https://github.com/yonicd/whereami/commit/5530dc2180f8dcffa28906210352ce77dd88f16e. i can traceback to the name of the file that was run. beyond that i think is a bridge too far to know the chunk it came from. 

i have a feeling it maybe can be done with `knitr:::knit_code` but that would involve importing `knitr`, which may be overkill.

**Comment by krlmlr** [comment]
I solved a similar problem in `rprojroot::thisfile()` and friends, but I'm not sure if this applies here. You can always declare a soft dependency and use _knitr_ only if it's installed.

**Comment by yonicd** [comment]
Thanks. I’ll take a look in that src code.

**Comment by yonicd** [comment]
@krlmlr in the end I pointed the script to `rprojroot::thisfile()` when `!( 'RStudio' %in% commanArgs( trainingonly = FALSE ) )`. thanks for pointing the function out to me. This issue https://github.com/yonicd/whereami/issues/2 came up right away.
