### ISSUE TITLE
Doesn't seem to work when invoked from Rscript

### ISSUE THREAD

**Issue by PedramNavid** [yonicd/whereami#2]
```
➜ Rscript --vanilla whereami.R
Error in file(con, "r") : cannot open the connection
Calls: cat -> <Anonymous> -> readLines -> file
In addition: Warning message:
In file(con, "r") :
  cannot open file '/var/folders/lh/msrbvmd94g1cjm_bl2_snb9w0000gn/T//RtmpGknMSu/file3d83ba1a2ba': No such file or directory
Execution halted
```

Contents of whereami.R: `whereami::whereami(path_expand=TRUE)`

**Comment by yonicd** [comment]
This script depends a lot on rstudioapi. I haven’t tested it yet on vanilla scripts. I’ll add it to the todo list. Thanks for trying out the package.

**Comment by yonicd** [comment]
it looks like [rprojroot](https://github.com/r-lib/rprojroot)::thisfile() is your best option for now.

**Comment by yonicd** [comment]
should work now in R/Rscript sessions. https://github.com/yonicd/whereami/commit/5f32b61019c075971d791f8e71cc73d81bc0110e
